version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            TAG=`git rev-parse HEAD`
            docker build -t 430047278637.dkr.ecr.us-east-1.amazonaws.com/hello-world:$TAG .
            eval $(aws ecr get-login --no-include-email --region us-east-1)
            docker push 430047278637.dkr.ecr.us-east-1.amazonaws.com/hello-world:$TAG
